services:
  - type: web
    name: cma_app
    env: docker
    dockerfilePath: ./Dockerfile
    ports:
      - 20000
    envVars:
      - key: PG_DB
        value: cma_live_db
      - key: PG_USER
        value: ibraphem
      - key: PG_PASSWORD
        value: 12345
      - key: PG_HOST
        value: cma_db

databases:
  - name: cma_db
    plan: free
    postgresVersion: 13
    properties:
      POSTGRES_DB: cma_live_db
      POSTGRES_USER: ibraphem
      POSTGRES_PASSWORD: 12345
