services:
  - type: web
    name: cma_app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PG_DB
        value: cma_live_db
      - key: PG_USER
        value: ibraphem
      - key: PG_PASSWORD
        value: 12345
      - key: PG_HOST
        value: cma_db
    autoDeploy: true

  - type: pserv
    name: cma_db
    plan: free
    env: postgres
    envVars:
      - key: POSTGRES_DB
        value: cma_live_db
      - key: POSTGRES_USER
        value: ibraphem
      - key: POSTGRES_PASSWORD
        value: 12345
