services:
  - type: web
    name: cma_app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PG_DB
        value: cma_live_db
      - key: PG_USER
        value: ibraphem
      - key: PG_PASSWORD
        value: 12345
      - key: PG_HOST
        value: ${databases.cma_db.internalHost}
    autoDeploy: true
    healthCheckPath: /

databases:
  - name: cma_db
    databaseName: cma_live_db
    user: ibraphem
    plan: free
    postgresMajorVersion: 14

